- nixopsaws/backends/ec2.py
Using deployment name instead of depl description for the backup operation
> Tag ec2 snaps with deployment name #4

- nixopsaws/resources/ebs_volume.py
A simple helpful change to reflect the EBS volume size in the output of nixops info
```
| batch_data |        Up       | ebs-volume [us-east-1a; 300 GiB] | vol-0a51ecdf22ca88edf                               |                |
| test_data  |        Up       | ebs-volume [us-east-1a; 250 GiB] | vol-014a609b8f5d08058                               |                |
| host_data   |        Up       | ebs-volume [us-east-1a; 300 GiB] | vol-0f983112e8c6a00e6                               |                |
| stage_data |        Up       | ebs-volume [us-east-1a; 200 GiB] | vol-08f7ffa4d582c2021                               |                |
```
> Displaying EBS size in nixops-info

- .travis.yml
- release.nix
- setup.py
- Use pname
- Consistent formatting and indentation
- Better meta description
- Use substituteAllInPlace
- Cleanup setup.py
- Use 19.09 channel in Travis CI
No real functional change.
> Cleanup release.nix and setup.py; bump to 19.09 in CI

- dev-shell
The `tarball` target does not exist in `nixops-aws`; this was copied over from
`nixops` and not removed on the plugin separation.
> Fix dev-shell exclusion reference to non-existent target

- coverage-tests.py
- nixopsaws/backends/ec2.py
- nixopsaws/resources/cloudwatch_metric_alarm.py
- nixopsaws/resources/ebs_volume.py
- nixopsaws/resources/elastic_file_system_mount_target.py
- nixopsaws/resources/elastic_ip.py
- nixopsaws/resources/iam_role.py
- nixopsaws/resources/route53_health_check.py
- nixopsaws/resources/route53_hosted_zone.py
- nixopsaws/resources/s3_bucket.py
- nixopsaws/resources/sns_topic.py
- nixopsaws/resources/vpc_customer_gateway.py
- nixopsaws/resources/vpc_dhcp_options.py
- nixopsaws/resources/vpc_internet_gateway.py
- tests.py
- tests/functional/__init__.py
- tests/functional/test_ec2_with_nvme_device_mapping.py
- tests/unit/test_device_name_to_boto_expected.py
This runs `autoflake --in-place **/*.py` to remove unused std library imports.
Note that there are quite a few unused non-stdlib imports as well, but removing
those is slightly riskier as they could have import side-effects, so they should
be done in a second pass with a reduced diff.
https://pypi.org/project/autoflake/
> autoflake: remove unused stdlib imports

- nix/generate-ec2-properties.py
Just requires fixing the print function, which works in python2 as well.
This fixes one of the stand-alone scripts for #29.
> generate-ec2-properties: make python3 compatible

- nixopsaws/backends/ec2.py
The cmp() function was removed in python3 [1], and while there is a workaround
listed, in this particular case we only need the `max` value and that's it.
Aside from being simpler and py2/py3 compatible, also happens to be more performant.
Partial work item for #29. Note that `2to3` *cannot* fix this particular one,
hence why it's being sent in a separate PR for code review.
[1] https://docs.python.org/3.0/whatsnew/3.0.html#ordering-comparisons
> py3 prep: remove use of cmp()

- nixopsaws/resources/__init__.py
- nixopsaws/resources/cloudwatch_log_group.py
- nixopsaws/resources/cloudwatch_log_stream.py
- nixopsaws/resources/ebs_volume.py
- nixopsaws/resources/elastic_file_system.py
- nixopsaws/resources/elastic_file_system_mount_target.py
This runs two more fixes that are safe to merge in python2 for continued
progress towards #29:
1. Converting `except T, R` to `except T as R`. Both work in python2, but only
the latter works in python3.
https://docs.python.org/3.0/whatsnew/3.0.html#changed-syntax
2. Converting module imports to relative imports.
> py3 prep: relative imports and exception syntax

- nixopsaws/backends/ec2.py
- nixopsaws/resources/ec2_keypair.py
In python3, `dict.items()` and `dict.values()` are iterators by defualt, so the
`iteritems` functions have been removed. In python2, these return a copy of the
keys, which has small runtime penalty but is unlikely to be material for NixOps.
Changing it to just `.items()` makes us both py2 and py3 compatible and prepares
us for the migration #29.
> py3 prep: replacing iteritems and itervalues

- nixopsaws/backends/ec2.py
- nixopsaws/resources/cloudwatch_metric_alarm.py
- nixopsaws/resources/elastic_file_system_mount_target.py
- nixopsaws/resources/route53_health_check.py
- nixopsaws/resources/route53_hosted_zone.py
- nixopsaws/resources/route53_recordset.py
In py2, map returned a list; in py3, it returns an iterator, which can't be indexed.
Per upstream guidelines [1], while it is possible to just add a list() cast,
it's more idiomatic to use a list comprehension for mapping. This is more
pythonic regardless, and still py2 compatible.
Partial progress towards #29
[1] https://docs.python.org/3.0/whatsnew/3.0.html#views-and-iterators-instead-of-lists
> py3-prep: fix map with list comprehensions

- nixopsaws/backends/ec2.py
- nixopsaws/resources/elastic_file_system_mount_target.py
- nixopsaws/resources/route53_recordset.py
In py2, filter returned a list; in py3, it returns an iterator, which can't be indexed.
Per upstream guidelines [1], while it is possible to just add a `list()` cast,
it's more idiomatic to use a list comprehension for filtering. This is more
pythonic regardless, and still py2 compatible.
Partial progress towards #29
CC @grahamc @AmineChikhaoui 
[1] https://docs.python.org/3.0/whatsnew/3.0.html#views-and-iterators-instead-of-lists
> py3-prep: fix filter with list comprehensions

- tests/functional/test_backups.py
- tests/functional/test_deploys_spot_instance.py
- tests/functional/test_ec2_rds_dbinstance.py
- tests/functional/test_ec2_with_nvme_device_mapping.py
- tests/functional/vpc.py
Casting to a list is a no-op in py2, but in py3 we cannot index [0] without it.
Partial progress towards #29.
This commit also removes unused imports from test case files as a general cleanup.
> py3 prep: foo.values() does not return an indexable list

- nixopsaws/resources/__init__.py
- nixopsaws/resources/ebs_volume.py
- nixopsaws/resources/ec2_placement_group.py
- nixopsaws/resources/ec2_rds_dbinstance.py
- nixopsaws/resources/ec2_security_group.py
- nixopsaws/resources/elastic_file_system.py
- nixopsaws/resources/elastic_file_system_mount_target.py
- release.nix
This does a 1-way migration to python3, and fully resolves #29.
Aside from the `release.nix`, there are no manual changes in this PR. It was
generated with:
2to3 -n -w **/*.py -x dict -x print
black .
We have already fixed the `print` function in a previous PR, as well as all of
the dictionary iterators. `2to3` is not particularly smart about this and will
add a `list()` cast just about everywhere otherwise.
> Migrate nixops-aws to python3

- nixopsaws/backends/ec2.py
Previously, the nixops-aws plugin was always calling
`known_hosts.update(old, new, val)`.
As of this commit [1], all arguments to the `update` function must be non-null.
While we could modify the `update` function in nixops to have the previous
behavior, it makes more sense for us to just call `add` when we mean add, and
`remove` when we mean remove.
[1] https://github.com/NixOS/nixops/pull/1233
CC @grahamc @TheWizardTower
> Bugfix: known_hosts update on nixops destroy

- nixopsaws/resources/ec2_keypair.py
In python3, the boto connection needs to take this as bytes.  Missed this change for #29. 
Also removes two unused variables nearby, which cause linter warnings.
CC @grahamc
> Bugfix: SSH public key creation has to be encoded into bytes

- nixopsaws/backends/ec2.py
- nixopsaws/resources/aws_vpn_connection.py
- nixopsaws/resources/aws_vpn_connection_route.py
- nixopsaws/resources/aws_vpn_gateway.py
- nixopsaws/resources/cloudwatch_metric_alarm.py
- nixopsaws/resources/ebs_volume.py
- nixopsaws/resources/ec2_common.py
- nixopsaws/resources/ec2_rds_dbsecurity_group.py
- nixopsaws/resources/elastic_file_system.py
- nixopsaws/resources/elastic_file_system_mount_target.py
- nixopsaws/resources/vpc.py
- nixopsaws/resources/vpc_customer_gateway.py
- nixopsaws/resources/vpc_dhcp_options.py
- nixopsaws/resources/vpc_egress_only_internet_gateway.py
- nixopsaws/resources/vpc_endpoint.py
- nixopsaws/resources/vpc_internet_gateway.py
- nixopsaws/resources/vpc_nat_gateway.py
- nixopsaws/resources/vpc_network_acl.py
- nixopsaws/resources/vpc_network_interface.py
- nixopsaws/resources/vpc_network_interface_attachment.py
- nixopsaws/resources/vpc_route.py
- nixopsaws/resources/vpc_route_table.py
- nixopsaws/resources/vpc_route_table_association.py
- nixopsaws/resources/vpc_subnet.py
Follow-up to #28, this removes non-stdlib imports with:
autoflake --in-place --remove-all-unused-imports **/*.py
except for the API `__init__.py` file.
No manual or functional changes, just cleanup.
> Remove unused imports

- nixops_aws/backends/ec2.py
Otherwise, the check would always fail.
> EC2 Backend: compare security groups as lists

- nixops_aws/nix/elastic-file-system-mount-target.nix
- nixops_aws/resources/elastic_file_system_mount_target.py
While working on #108 I tested the EFS mount targets and figured this might be a desired change. A user can now finally pass a NixOps managed resource as subnet and doesn't have to hardcode the subnet's identifier as string.
> efs mount targets: allow passing a subnetid as Nix attrset

- nixops_aws/resources/ec2_rds_dbinstance.py
Otherwise this may be considered a failed state during provisioning.
> rds: accept configuring-enhanced-monitoring as a valid state

- nixops_aws/backends/ec2.py
The AWS API provides us with some non-sensical device names that might
have nothing to do with reality. For some reason there is weird renaming
going on from the values that boto3 (the AWS API bindings) returns to us
to what we actually configure on the machine. Apparently nowadays some
volumes are not properly being mapped from AWS to NixOps. Amazon doesn't
appear to give much of a guarantee (or any) in terms of device names.
Accepting the "real" device name instead of the mapped device name gets
rid of issue #105. In an ideal world Amazon would be providing WWUIDs,
device paths or some other attribute that they can define with the block
device. Since that doesn't (seem to) exist we must live with this change
until someone comes up with a better solution.
> volumes: treat non-aliased devices as equivalent to aliased ones

- nixops_aws/ec2_utils.py
- nixops_aws/nix/cloudwatch-log-group.nix
- nixops_aws/nix/cloudwatch-log-stream.nix
- nixops_aws/nix/default.nix
- nixops_aws/nix/ec2-rds-dbinstance.nix
- nixops_aws/nix/elastic-file-system-mount-target.nix
- nixops_aws/nix/elastic-file-system.nix
- nixops_aws/nix/iam-role.nix
- nixops_aws/nix/rds-subnet-group.nix
- nixops_aws/nix/s3-bucket.nix
- nixops_aws/nix/sns-topic.nix
- nixops_aws/nix/sqs-queue.nix
- nixops_aws/resources/ec2_rds_dbinstance.py
- nixops_aws/resources/rds_db_subnet_group.py
- nixops_aws/resources/types/ec2_rds_dbinstance.py
- nixops_aws/resources/types/rds_db_subnet_group.py
Create resources for subnet groups to allow RDS instances to be spawned in a VPC. Closes #57, #13, #6. 
cc @RaitoBezarius -- I didn't think to look for your PR before I wrote this (sorry :() but also that one is pre-py3, etc.
> RDS: Support VPC

- .github/workflows/ci.yaml
- nixops_aws/nix/route53-recordset.nix
- nixops_aws/resources/route53_recordset.py
Allow the values in a route53 recordset to be ElasticIP resources, in
the same way that they are allowed to be machine resources, and resolve
the ip address of the ElasticIP when creating the recordset.
Fixes #117
----
#
> Allow Route53 recordsets to point at EIPs

- nixops_aws/backends/ec2.py
- nixops_aws/nix/ec2.nix
- nixops_aws/resources/route53_recordset.py
- Fix a type error in `ec2.nix`
- Allow any machine to be used in a Route53 record set, not just EC2 machines
Currently, the nix option type allows any machine to be specified, but the python code expects an EC2 machine, resulting in a deadlock when an unexpected machine type is used.
> Fix type error in ec2.nix and overly strict typing in route53_recordset.nix

- nixops_aws/nix/ec2.nix
It has been defined as the identity function for a long time.
See https://github.com/NixOS/nixpkgs/pull/129993
> Remove deprecated mkFixStrictness call

- nixops_aws/backends/ec2.py
Somewhat duplicate of #151 I just noticed, but improving one more line, for route53.
Independently discovered. Fixes a problem for me when deploying an ec2 instance with a pre-existing volume.
> Fix None access using _connect methods

- nixops_aws/backends/ec2.py
Used to be something like "None doesn't have a zone field".
> Add proper error message for when volume is missing

- nixops_aws/backends/ec2.py
By default, this is prohibited and the call returns a `Resource.AlreadyAssociated` error.
> Pass `allow_reassociation=True` when reassociating Elastic IP

- nixops_aws/resources/route53_recordset.py
For the first run, it was
The domain name 'foo.bar' does not end in the zone name 'None'. You have to specify the FQDN for the zone name.
because the self.zone_name is only initialized at the end.
Now it prints the zone name correctly:
The domain name 'foo.bar' does not end in the zone name 'bar.'. You have to specify the FQDN for the zone name.
`zone_name` is always defined. The git blame does not provide an explanation for the choice of `self.zone_name`, so it isn't unreasonable to assume a mistake.
> Fix route53RecordSet error message

- nixops_aws/backends/ec2.py
When using nixpkgs after commit https://github.com/NixOS/nixpkgs/commit/24e33a4d2e41, I get the error
```
building all machine configurations...
error:
Failed assertions:
- The option definition `ec2.hvm' in `/tmp/nixops-tmpgkc5bopf/physical.nix' no longer has any effect; please remove it.
Only HVM instances are supported, so specifying it is no longer necessary.
```
This change allows me to update my ec2 instances. According to the referenced commit message, "Paravirtualized EC2 instances haven't been supported since 2017." I am not sure exactly what that means. Is the option is still required by some Nixops users?
> Don't set removed ec2.hvm option

- nixops_aws/nix/ec2.nix
Solves a problem where i686, 32-bit is selected for some instance types.
> Prefer known and 64 bit cpus
